// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU1keP-4fVUhqMSEqm0lfcltjI8QhkvE0',
    appId: '1:233590654518:web:216af5e2eb118bfbf8ba97',
    messagingSenderId: '233590654518',
    projectId: 'chat-app-1a859',
    authDomain: 'chat-app-1a859.firebaseapp.com',
    storageBucket: 'chat-app-1a859.firebasestorage.app',
    measurementId: 'G-KNNSYYY434',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuyekbsWsTIp0OXra-ErDWw-UphlC7adc',
    appId: '1:233590654518:android:197b2db13f9b8a27f8ba97',
    messagingSenderId: '233590654518',
    projectId: 'chat-app-1a859',
    storageBucket: 'chat-app-1a859.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiRacFb6p0kIotz1rIE-A7Dn2h48IhoCo',
    appId: '1:233590654518:ios:349eb9f124bc7718f8ba97',
    messagingSenderId: '233590654518',
    projectId: 'chat-app-1a859',
    storageBucket: 'chat-app-1a859.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiRacFb6p0kIotz1rIE-A7Dn2h48IhoCo',
    appId: '1:233590654518:ios:349eb9f124bc7718f8ba97',
    messagingSenderId: '233590654518',
    projectId: 'chat-app-1a859',
    storageBucket: 'chat-app-1a859.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU1keP-4fVUhqMSEqm0lfcltjI8QhkvE0',
    appId: '1:233590654518:web:30dee6066f6bdb7af8ba97',
    messagingSenderId: '233590654518',
    projectId: 'chat-app-1a859',
    authDomain: 'chat-app-1a859.firebaseapp.com',
    storageBucket: 'chat-app-1a859.firebasestorage.app',
    measurementId: 'G-3FJFRVKLKS',
  );
}
